---

- name: Prepare
  hosts: all
  gather_facts: false
  tasks:
    - name: Install required packages
      yum:
        name:
          - iproute
          - iptables-services
          - openssh-server
        state: present
    - name: Enable and sshd
      systemd:
        name: sshd
        state: started
        enabled: yes
